version: '3.2'
services:
  pg:
    image: postgres:10.1
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lingvodoc
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    container_name: ngx
    ports:
      - "80:6543"
    volumes:
      - ./frontend:/dist
      - ./nginx:/etc/nginx/conf.d
      - ./sock:/sock
    depends_on:
      - pg
      - api
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
  api:
    build: ..
    depends_on:
      - pg
      - redis
    container_name: ld
    volumes:
      - ./frontend:/dist
      - ./sock:/sock
    command: "python3.4 setup.py --react-frontend /dist install && sleep 5 && gunicorn --paster docker.ini"
    ports:
      - "6543:6543"
